const String siteUrl = "https://duk.shiwkesh.in";
const String baseUrl = "https://duk.shiwkesh.in"; //PROD
// const String baseUrl = "https://dev.univsports.in"; //DEV
// const String baseUrlFiles = "https://files.univsports.in/storage";
// const String baseUrlFileUpload = "https://files.univsports.in";
// const String socketUrl = 'https://chat.univsports.in:4000';
// const String liveUrl = 'https://live.univsportatech.com';
// const String liveUrlFiles = 'https://live.univsportatech.com/storage';
const String QRFiles = "https://files.univsports.in/storage/uploads/qrcodes";
